# This file is a template, and might need editing before it works on your project.
---
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - hugo
  except:
    - master

build:
  stage: build
  script:
    - hugo
    - tar czf public.tar.gz public deploy.sh
  artifacts:
    paths:
      - public.tar.gz
  only:
    - master

deploy:
  stage: deploy
  before_script:
    - apk update && apk add openssh-client bash
  script:
    # run ssh-agent
    - eval $(ssh-agent -s)

    # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'

    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    # ssh commands here

    - scp public.tar.gz gitlab@$SSH_HOSTNAME:. 
    - ssh gitlab@$SSH_HOSTNAME -C 'tar xzf public.tar.gz; chmod +x deploy.sh; ./deploy.sh'
