---
image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  TZ: America/Toronto

stages:
  - pages

pages:
  stage: pages
  script:
    - echo "commit = \"$CI_COMMIT_SHA\"" > data/git.toml
    - hugo --gc --minify
  artifacts:
    paths:
      - public
  only:
    - main
