baseURL = "https://jcdl.net/"
languageCode = "en-ca"
title = "~jcdl"
theme = "noteworthy"

[params]
  twitter = "https://twitter.com/jagger27"
  github = "https://github.com/jagger27"
  gitlab = "https://gitlab.com/jagger27"

