baseURL = "/"
languageCode = "en-ca"
title = "jcdl"
theme = "jcdl"
pygmentsUseClasses = true
relativeURLs = true 

[params]
  pageTitle = "jcdl/blog"
  configDir = "config/"
  src = "https://gitlab.com/jagger27/blog/"
  commitPath = "-/commit/"

[links]
  twitter = "https://twitter.com/jagger27"
  github = "https://github.com/jagger27"
  gitlab = "https://gitlab.com/jagger27"
