name = "transpile"
license = "AGPLv3"
licenselink = "https://gitlab.com/transpile/blog/-/blob/main/themes/transpile/LICENSE"
description = "The bespoke theme for transpile.net"
tags = []
features = []
min_version = "0.117.0"

[author]
  name = "Danielle De Leo"
  homepage = "https://transpile.net"
