name = "Jcdl"
license = "MIT"
licenselink = "https://gitlab.com/jagger27/blog/-/blob/master/themes/jcdl/LICENSE"
description = ""
tags = []
features = []
min_version = "0.41.0"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
